version: '3.0'

services:

  gogs:
    restart: unless-stopped
    image: gogs/gogs
    volumes:
      - gogs-vol:/data
    ports:
      - "10022:22"
      - "3000:3000"
    depends_on:
      - mariadb

  mariadb:
    restart: unless-stopped
    image: mariadb
    volumes:
      - mariadb-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"

  jenkins:
    restart: unless-stopped
    image: jenkins
    volumes:
      - jenkins-vol:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

  #artifactory:
  #  restart: unless-stopped
  #  image: docker.bintray.io/jfrog/artifactory-oss
  #  volumes:
  #    - artifactory-vol:/var/opt/jfrog/artifactory
  #  ports:
  #    - "8081:8081"

  cadvisor:
    restart: unless-stopped
    image: google/cadvisor:latest
    privileged: true
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro
    ports:
      - "8089:8080"

  #elk:
  #  restart: unless-stopped
  #  image: sebp/elk
  #  volumes:
  #    - elk-vol:/var/lib/elasticsearch
  #  ports:
  #    - "5601:5601"
  #    - "9200:9200"
  #    - "5044:5044"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/tmp/prometheus.yml
    ports:
      - "9999:9090"
    command: -config.file=/tmp/prometheus.yml

volumes:
  jenkins-vol:
  mariadb-vol:
  gogs-vol:
  #artifactory-vol:
  #elk-vol:
